source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'YLBCommon_Example' do
  pod 'YLBCommon', :path => '../'
  pod 'YLBProUI', :git => 'https://github.com/YuliboTeam/YLBProUI.git'
  pod 'UMCCommon'
  # 集成微信(完整版14.4M)
  pod 'UMCShare/Social/WeChat'
  
  target 'YLBCommon_Tests' do
    inherit! :search_paths

    
  end
end
